# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-22 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picURL',
            field=models.URLField(blank=True, null=True),
        ),
    ]