# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-23 11:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160522_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='pic_url',
            new_name='picture_URL',
        ),
    ]